image: nixos/20.03
sources:
  - https://git.sr.ht/~chreekat/usort
tasks:
  - nix-build: |
      cd usort
      nix-shell -A shells.ci-shell --run 'cachix use miso-haskell'
      nix-build --quiet
  - shells-check: |
      cd usort
      nix-shell -A shells.ci-shell --run 'cachix use miso-haskell'
      for shell in ci-shell shell client-shell; do
        nix-shell . -A $shell --run "echo Shell $shell ok."
      done
