nix build:
  image: nixpkgs/nix:nixos-20.03
  script: |
    nix-shell -A shells.ci-shell --run 'cachix use miso-haskell'
    nix-build --quiet
    nix-shell -A shells.shell --run 'echo shell ok.'
    nix-shell -A shells.client-shell --run 'echo client-shell ok.'
