name: usort
version: '0.2.0.0'
synopsis: With usort, the sort is you!
description: Please see README.md
category: Web
author: Bryan Richter
maintainer: b@chreekat.net
copyright: Bryan Richter
license: AGPL-3
license-file: LICENSE.md
github: chreekat/usort
homepage: http://github.com/chreekat/usort#readme
dependencies:
- base >=4.7 && <5
- text >=1.2.2.0
library:
  source-dirs: src
  exposed-modules:
  - USort
  - UserCompare
  - Types
  dependencies:
  - formatting >=6.2.2
  - haskeline >=0.7.2.1
executables:
  usort:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O
    dependencies:
    - usort
tests:
  usort-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -O
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - usort
    - tasty
    - tasty-quickcheck
    - tasty-hunit
