name: usort
version: '0.3.0.0'
synopsis: With usort, the sort is you!
description: Please see README.md
category: Web
author: Bryan Richter
maintainer: b@chreekat.net
copyright: Bryan Richter
license: AGPL-3
license-file: LICENSE.md
github: chreekat/usort
homepage: http://github.com/chreekat/usort#readme
dependencies:
- base >=4.7 && <5
- text >=1.2.2.0
flags:
  pedantic:
    description: "Use -Wall -Werror"
    manual: true
    default: false
when:
    - condition: flag(pedantic)
      ghc-options: [-Wall, -Werror]
library:
  source-dirs: src
  exposed-modules:
  - USort
  - UserCompare
  - Types
  - SplitItems
  dependencies:
  - formatting >=6.2.2
  - haskeline >=0.7.2.1
executables:
  insort: &exe
    main: Main.hs
    source-dirs: app-insort
    dependencies:
    - usort
  usort:
    << : *exe
    source-dirs: app-usort
tests:
  usort-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - usort
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - tasty-golden
